### ISSUE TITLE
API: Return all tags from a given category

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#10]
- Client requests all tags available for a certain category (tags are LAKE resources with an aic:cat property pointing to a resource, and a skos:prefLabel property; the combination of the two properties is unique for all aictype:Tag resources)
- Server returns a list of URIs, labels and category URIs in JSON(-LD) format

**Comment by RudyOnRails** [comment]
@awead @scossu can we close this one?
