### ISSUE TITLE
Write-once-only (WRO) and UID validation

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#100]
Implement WRO and UID validation.

**Comment by awead** [comment]
In looking at the write-once fields, the only field that looks like it would be managed by Hydra would be the department field. The others appear as though they would be coming from Geneva.

**Comment by scossu** [comment]
aic:legacyUid for aictype:Asset is also WRO. This is managed by Hydra. 
Also there was a missing WRO note for aic:uid, which I have added to the content model spreadsheet.

**Comment by scossu** [comment]
According to discussion, aic:legacyUid can be made read-only in the interface but it is not critical to leave out back-end validation at this point. 
Since this is the only use case that justifies writing the WRO mechanism, this issue can be moved back to a later phase.
