### ISSUE TITLE
Lists can be modified by certain users

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#103]
Given there is a List "conservation tags" which Conservation users have read and write access
As an authenticated user in the Conservation group
I should see an option to add or remove items to the list

**Comment by scossu** [comment]
Related to #104

**Comment by awead** [comment]
@scossu can we move this to beta1 as it pertains to #130 ?

**Comment by scossu** [comment]
Moving to beta2 along with #104
