### ISSUE TITLE
Restrict changes to lists

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#104]
Given there is a List "conservation tags" which Conservation users have read and write access
As an authenticated user not in the Conservation group
I should not see an option to add or remove items to the list

**Comment by scossu** [comment]
Related to #103

**Comment by awead** [comment]
@scossu can we move this to beta1 as it pertains to #130 ?

**Comment by scossu** [comment]
Yes.

**Comment by scossu** [comment]
Beta1 users will be tightly controlled and we can rely on their behavior to avoid having list items get out of control. Moving to beta2.

**Comment by scossu** [comment]
Migrated to CITS.
