### ISSUE TITLE
Department ID stored in LAKE not showing in LAKEshore 

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#105]
E.g. Work # aeb0330a3f98b4f0d2e04e02f77b8f1f shows aic:deptUid with value "20" in LAKE but is empty in LAKEshore work display page.

**Comment by awead** [comment]
I'm not seeing aic:deptUid in the content model, but I am seeing it in the sample resource. I have aic:department for Work as a ListItem. Which should we use?

**Comment by scossu** [comment]
That is right, there is a discrepancy. Truth is that we do not have departments as resources in LAKE yet, so aic:deptUid should be used for the time being. 

I will change the content model doc accordingly until department URIs are available.
