### ISSUE TITLE
Change typeUid to exhibitionTypeUid for Exhibitions

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#107]
See content model document for reference. 

This is to avoid possible naming conflicts with other resource types.

**Comment by awead** [comment]
@scossu note, the example exhibition:
http://dams01-test.artic.edu/fcrepo/rest/prod/11/30/e7/ca/1130e7ca-9327-4390-9364-3946806b88ca
still has typeUid. I've changed this in the fixture, but FYI...

**Comment by scossu** [comment]
@awead: thanks for the note. I updated the resource in Fedora.
