### ISSUE TITLE
Display asset thumbnail on ingestion second step (metadata form)

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#115]
After a batch of assets is ingested in LAKEshore, the metadata form contains title fields for individual files. However, it is impossible to tell which file each field refers to. 

The best solution for the user would be to have a thumbnail of the asset near the individual fields (assuming that we may have more than just the title in this area in the future). If this is not possible, we should discuss a different way to achieve this.

**Comment by awead** [comment]
This is a batch edit page. Any changes to the fields apply to all files in the group.

**Comment by scossu** [comment]
I am referring to the "Title <n>" field that is ediable for individual files.

**Comment by awead** [comment]
This was originally the title of the file that was uploaded, but you wanted it changed to the auto-generated pid. If you revert it to the original behavior of the file name, the user would be able to tell which was which and rename it accordingly.

Thumbnails wouldn't be available at this point because they're being generated.

**Comment by scossu** [comment]
Title (skos:prefLabel) and UID (aic:uid) are two separate fields. 

The UID is assigned by Sufia and should never be editable. The title is set to the UID by default but should be editable in the post-upload form and in the edit form.

**Comment by scossu** [comment]
See #117

**Comment by awead** [comment]
The uid field it not editable, it's just the label field being set with the same content as the uid.

**Comment by scossu** [comment]
Bringing this conversation to #117.

**Comment by scossu** [comment]
Needs workaround. Pushing to beta2.

**Comment by scossu** [comment]
Migrated to issue tracking system.
