### ISSUE TITLE
Remove "Feature" link from Action menus

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#116]
Remove link to "Feature" action from action menu on all view pages (assets and non-assets).

**Comment by awead** [comment]
Do you want this available in edit mode, or do you want it removed completely, including the section of the front page that displays featured items.

**Comment by scossu** [comment]
We are not planning to use the "featured" feature anywhere. Ideally the functionality should be disabled across the application, but if that has implications, hiding it would be enough. 

The featured item list is already hidden in the home page.
