### ISSUE TITLE
Change landing page for anonymous users

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#119]
Since LAKEshore is not meant to be public-facing, all users who have access to any kind of information should be logged in. 

Home page should be accessible only to logged in users. The default landing page for anonymous users should be the log-in page.

**Comment by scossu** [comment]
For the record: this fix applies to all pages, not only to the landing page, as previously discussed. 

Any page accessed as a non-authenticated user redirects to the login page.

**Comment by awead** [comment]
Yep. It was a one-line change:
https://github.com/aic-collections/aicdams-lakeshore/blob/master/app/controllers/application_controller.rb#L15
