### ISSUE TITLE
API: Delete resource

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#12]
- Client wants to delete a resource
- In this phase, this is achieved by sending a direct DELETE request to LAKE. In a second phase, soft-delete operations can be implemented. This may not involve middleware if this functionality is supported directly by Fedora.

**Comment by scossu** [comment]
the LAKEshore API should offer a DELETE method. 
In this phase this method simply sends a DELETE request to LAKE and returns the return code from LAKE.
