### ISSUE TITLE
Rename "Files" to "Assets" across all application pages

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#121]
The term "Files" is meant to be used for instances of assets, i.e. when multiple files will be allowed for an asset. 

This term should be replaced in all application pages where relevant, including: 
- Quick search bar
- Dashboard
- "My Files" page and tabs in user profile and breadcrumbs

**Comment by surreal8** [comment]
@scossu please test on dev

**Comment by scossu** [comment]
Resolved with 2340a60ee3de2933ee7bf76c8839bd47b4662a3f
