### ISSUE TITLE
Using ::RDF::Vocab::IANA.describedby causes Ldp::Conflict

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#128]
0a06e90f8eceabcb7f19c16caffd2fafcf982b21 introduced a problem with the `::RDF::Vocab::IANA.describedby` predicate. My guess is that it's reserved somehow for PCDM and using it for other properties causes problems. The easiest solution would be use our own predicate.

**Comment by scossu** [comment]
We can use aic:describedBy as an alternative. I will change the content model accordingly. 

That aside, who is complaining about that? Fedora or Hydra? I wonder if a general-purpose property like iana:describedBy needs to be reserved by any application for exclusive use.

**Comment by awead** [comment]
I don't know. I haven't had time to investigate.

**Comment by awead** [comment]
No longer and issue with Sufia 7.
