### ISSUE TITLE
Redesign non-asset view page

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#129]
- Duplicate outstanding properties just below title
- Add message if no assets are related to resource
- Show all links to other resource in default link color (currently blue)
- Crop strings to 128 characters and add "show/hide full text" links

![lakeshore_objpage_template](https://cloud.githubusercontent.com/assets/4306733/11110469/cca291f0-88c1-11e5-81de-d477f56db59c.png)

**Comment by surreal8** [comment]
completed with commit cc19d6202e6c45f5be62585044e202da0ce224cd
