### ISSUE TITLE
Upload new version

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#13]
- User uploads new file to replace existing asset source
- Application verifies that file is in list of accepted MIME types, optionally performs thorough validation of image file (this may be tackled in separate scope)
- Application proceeds with update if validation passes, throws exception if it fails

**Comment by awead** [comment]
Where is the list of accepted MIME types?

**Comment by scossu** [comment]
https://github.com/aic-collections/aicdams-docs/blob/master/LAKE/cmodels_mime_types.md
