### ISSUE TITLE
Create UI elements for lists and list items

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#130]
Create a page displaying all the list items aggregated by list, and a UI to add and remove items from each list.

Each list item has a label (madatory) and a description (optional) field. 

Stefano to provide layout.

**Comment by awead** [comment]
Error reporting will be done in #131

**Comment by scossu** [comment]
@awead See rough layout sketch of list edit page (showing all lists) and list item edit page (showing individual lists)

![lakeshore_list items_form_layout_sketch](https://cloud.githubusercontent.com/assets/4306733/11596842/42f74e1e-9a7d-11e5-87ed-e64e4c55b229.jpg)

Hierarchical lists are trickier and need extra UI features, and should be covered in a separate round.

**Comment by awead** [comment]
@scossu do we need the ability to add new list types?

**Comment by scossu** [comment]
No, users can only modify existing lists. New lists are only created by developers, and at the moment we can create them manually.
