### ISSUE TITLE
Assigning invalid relationships

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#14]
- User adds property to an asset with the following triple: <asset123> aic:represents <file456>
- According to content model, aic:represents has range aictype:NonInfoResource
- <file456> has type aictype:Instance, which is not a sub-type of aictype:NonInfoResource
- Relationship assignment is invalid and throws an exception

**Comment by awead** [comment]
Similar question: aic:represents isn't a current predicate, I believe.

**Comment by scossu** [comment]
See comment to #15

**Comment by awead** [comment]
Because these relationships are definable only on GenericFiles, attempting to assign it to something that's not, immediately results in an error:

``` ruby
> class Foo < ActiveFedora::Base; end
> foo = Foo.create
> Work.all.first.representations = [Foo]
ActiveFedora::AssociationTypeMismatch: GenericFile(#70279219079340) expected, got Class(#70279171077600)
```

Furthermore, the UI would limit it so that only GenericFile objects would make it to the controller. Ther user would need console-level access in order to assert invalid relationships.
