### ISSUE TITLE
Quick search in My Collections and My Assets keeps resource type in search terms

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#141]
Steps to reproduce: 
- Select "Actors" from quick search drop-down menu
- Leave search fields blank and click "Go" button
- A list of actors is shown
- From the same page, select either "My Collections" or "My Assets" from the quick search menu and hit "Go"

Result: in both cases, search terms still contain the "Resource type: Actor" tag and therefore search results are empty
Expected: resource type should be cleared when searching for My Collections or My Assets.

**Comment by scossu** [comment]
This also happens for "All" option.

**Comment by awead** [comment]
The only way to fix this would be to change the way we're limiting search results to the different CITI resources and not use the resource type facet. You'll note that you see the same behavior with any facet used in a search: facet terms are not cleared when performing successive searches. This is a Blacklight behavior.

**Comment by scossu** [comment]
I would like to explore the possible options later on; the current behavior is counter-intuitive. 

Moving to beta2.
