### ISSUE TITLE
Cannot set permissions for groups external to logged in user

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#145]
In permissions tab of asset edit page, when I select the pull down menu to share the resource with other departments, only "registered" and the logged in user's department are shown.

All existing departments should be available for sharing.

**Comment by awead** [comment]
Where should the list of departments come from?

**Comment by scossu** [comment]
They should be all the registered departments (roles?) in LAKEshore. The same group that the owner's department showing in the drop-down menu belongs to.
