### ISSUE TITLE
Occasional error pages on full catalog page

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#148]
Test has currently about 100K CITI entities imported and indexed. 

When requesting /catalog with no filters, I get error pages intermittently.

**Comment by awead** [comment]
If you could notate the approximate local times these occur, I can look for them in the logs.

**Comment by scossu** [comment]
I just had it occur on 2015-12-10T13:25:05 server time.

**Comment by scossu** [comment]
Never mind. Fedora was having GC issues. The error is not showing up any more.
