### ISSUE TITLE
Assigning valid relationships

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#15]
- User adds property: `<asset123> aic:represents <person789>`
- `<person789>` has type aictype:Agent, which is a sub-type of aictype:NonInfoResource
- Relationship is valid and application proceeds with updating resource

**Comment by awead** [comment]
Is aic:represents a current predicate?

**Comment by scossu** [comment]
Not any more. The relationship should be `<person789> aic:hasRepresentation <asset123>`. But the overall rule still applies: the range of `aic:hasRepresentation` should be an aic:Asset or subtype thereof, as per content model.

**Comment by awead** [comment]
I don't think these kinds of validations are necessary. Any resource can have a representation that is a GenericFile, AKA an asset:
 https://github.com/aic-collections/aicdams-lakeshore/blob/master/app/models/concerns/resource_metadata.rb#L76-L78
So long as the object is a GenericFile, it'll allow it.

**Comment by awead** [comment]
Sorry, I mean any `AICType.Resource`
