### ISSUE TITLE
Some text document thumbnail oversized in asset view page

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#152]
In some asset view pages, the asset thumbnail appears way oversized and overlaps with the metadata area. This seems to happen with .docx text files. 

See screenshot.

![screenshot_2015-12-16_08-11-59](https://cloud.githubusercontent.com/assets/4306733/11876606/584c1226-a4b0-11e5-8913-3972160da0e1.png)

**Comment by scossu** [comment]
@surreal8 As a quick fix, can you add some CSS rules to constrain size until fix the thumbnail generator?

**Comment by surreal8** [comment]
I see this issue only in FF, Chrome and Safari are fine. Let me know if otherwise.
