### ISSUE TITLE
Improve relationship list in non-asset view

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#155]
- Reword header: "Preferred Representations" -> "Preferred Representation" 
- Reword field label: "Resource" -> "Resource type"
- Add aic:uid and skos:prefLabel to each resource in the list (currently there is an "identiifer" field which is empty)

**Comment by surreal8** [comment]
ok, trying again

**Comment by scossu** [comment]
Good for production.
