### ISSUE TITLE
Finalize available fields in asset edit view

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#157]
- Hide fields that are not in scope for beta 1
- Associate lists with appropriate fields
- Rearrange field order 

The final list of required fields and their order is pending discussion with DEA.

**Comment by scossu** [comment]
List of changes: 
- Hide or remove:
  - Batch UID
  - Contributor
  - Resource created
  - Described By
  - Pref label
  - Resource label
  - Legacy UID
  - Rights
  - Same as
  - Resource updated
  - Icon
  - Document ids
  - Representation ids
  - Pref. repr. ids
  - Transcript
  - Comments
- Rename and rearrange the remaining fields in the following order: 
  - Document Type
  - Title
  - Creator
  - Abstract or Summary
  - Keyword
  - Language
  - Rights Holder
  - Asset Capture Device
  - Compositing -> Image Compositing (list)
  - Light Type -> Image Capture Light Type (list)
  - View -> Image View (list)

**Comment by surreal8** [comment]
Removed fields, moved title to top, need to move Document Type and rename fields

**Comment by scossu** [comment]
That looks good for beta1. You can close the issue as soon as the PR is merged.

**Comment by scossu** [comment]
@awead Already tested in dev. You can deploy to production.
