### ISSUE TITLE
Associate lists with vocabulary-based properties

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#164]
Associate the following properties and lists:
- aic:status -> Status
- aic:digitizationSource -> Digitization Source
- aic:documentType -> Document Type
- aic:tag -> Tag
- aic:category -> Comment Category
- aic:conservationDocType -> Conservation Document Type
- aic:specialImageType -> Conservation Image Type
- aic:deptCreated -> Department
- aic:compositing -> Compositing
- aic:lghtType -> Light Type
- aic:view -> View

Change edit page fields for the above properties to pull-down menus.

**Comment by awead** [comment]
@scossu I won't be able to do department created because it's currently tied to the user table. Once we have shib. authentication we could tie it in at that point.

**Comment by scossu** [comment]
That is fine for now. We are concerned with displaying drop-down menus at the moment, and deptCreated is read-only anyway.

**Comment by awead** [comment]
@scossu I'm also omitting aic:conservationDocType and aic:specialImageType because they're only defined on ConservationMetadata, which isn't available yet.

**Comment by scossu** [comment]
:ok_hand:

**Comment by scossu** [comment]
Restrict required properties to:
- aic:status
- aic:documentType
- aic:tag

The following are "nice to have"s if not too laborious:
- aic:view
- aic:digitizationSource
- aic:lightType
- aic:compositing

Others can be implemented in beta2 or when those properties are available for UI editing.

**Comment by scossu** [comment]
Good for production.
