### ISSUE TITLE
Assigning valid types

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#17]
- User attempts to assign aicmix:WebPublished to `<asset1234>`
- aicmix:WebPublished is not a disjointed type and can be assigned to any resource
- Application proceeds to updating resource

**Comment by awead** [comment]
Are these additional rdf types that are assigned to assets?

**Comment by scossu** [comment]
Yes. But this use case is not relevant any more and can be closed, since disjointed types are managed via Sufia's content models (Image, Text, etc.)
