### ISSUE TITLE
Finalize displayed fields in asset view page

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#173]
Hide or remove the following fields:
- Contributor
- Described by
- Pref label
- Resource label
- Rights
- Same as
- Icon
- Document ids
- Representation ids
- Pref. repr. ids
- Transcript
- Comments

Rename and resort the remaining fields in the following order:
- UID
- Legacy uid
- Document Type
- Status
- Resource created
- Dept created -> Created By Department
- Resource updated
- Abstract or summary
- Batch uid -> In Batch
- Language
- Publisher
- Rights Holder
- Keyword
- Compositing -> Image Compositing
- Light type -> Image Capture Light Type
- View -> Image View
- Asset Capture Device
- Digitization Source

**Comment by awead** [comment]
created_by is missing from the list, and currently keyword is getting crossed with tag. Would you prefer "Keyword" or "Tag"?

**Comment by awead** [comment]
tags are also missing.

**Comment by awead** [comment]
Sorry, nevermind. Tag is getting crossed with keyword.

**Comment by scossu** [comment]
Keywords are what is labeled 'Tags' in the edit view. It is a multi-select box. They should be actually 'Tags' in the view page as well. 

Agree on created_by (dcterm:creator), it should be added to the list.
