### ISSUE TITLE
Asset status is "invalid" by default

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#179]
When I upload an asset, its status is set to "invalid" by default. It should be "active".

**Comment by awead** [comment]
@scossu I'm not seeing this anymore, however, I knew I was earlier. Have you seen this happen recently? I've just tested locally, and on test and prod, but can't replicate it.

**Comment by scossu** [comment]
I saw this happen consistently fairly recently, but it seems to be gone now. Closing.
