### ISSUE TITLE
Validate tag uniqueness

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#18]
- User attempts to create tag with label “X-ray photo” in category “Conservation”
- Application checks if a resource of type aictype:Tag with the same label and same category already exists
- If such resource exists, application returns 409 Conflict. Otherwise, tag is created.

**Comment by awead** [comment]
Are tags now ListItem types?

**Comment by scossu** [comment]
Yes. This applies to the rdfs:label property, which should be unique among ListItems belonging to the same List. 

If this requires considerable time we can discuss alternative solutions or push it back. Initially we will have only admins create list items so the mess is contained.

**Comment by awead** [comment]
Ok, this makes sense now. The validation isn't difficult, but the GUI required for managing list items will take additional time.

**Comment by awead** [comment]
A 409 status would only be applicable if this was an API. Since these are just ActiveFedora objects, the standard practice is to add an error message to the object and report that in the GUI or console.
