### ISSUE TITLE
"Select folder" option missing in upload page in Firefox

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#190]
The "select folder" button is available in Chrome but not in Firefox.

**Comment by awead** [comment]
This feature is only available in Chrome:
https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support#folder-selection

**Comment by scossu** [comment]
Understood. Good to let users know. 

I will remove milestone and priority leave this open until this is supported by the upstream project.

**Comment by scossu** [comment]
Will reopen in CITS if issue is raised by end users.
