### ISSUE TITLE
File name not shown in upload form when upload fails

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#193]
When a file upload fails its file name is not shown in the upload form. This makes it hard to find out which file failed and re-submit it. 

![screenshot-2016-01-04_10-55-07](https://cloud.githubusercontent.com/assets/4306733/12095063/ede2c38c-b2d1-11e5-9cb3-51cd8689aca3.png)

**Comment by awead** [comment]
This will be fixed in projecthydra/sufia#1509

**Comment by awead** [comment]
Not available until #201
