### ISSUE TITLE
Image upload fails if file name has no extension

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#204]
Uploading an image file without file extension results in a failed upload. Adding the extension (e.g. .tif) the file is ingested without problem.

**Comment by scossu** [comment]
@awead , does this have to do with validation? In that case, can validation be done using more reliable methods such as magic number?

**Comment by awead** [comment]
The file extension is how Lakeshore determines mime_type, which is required when determining still image or text type.

**Comment by awead** [comment]
Looks like it's possible via https://github.com/blackwinter/ruby-filemagic but I've never used it. Without knowing how this would impact the current codebase, I can't guess how long it would take to implement properly. If you would like to add it to this milestone, it would impact completing other issues.

**Comment by scossu** [comment]
Actually it makes more sense to require a file name extension as a matter of good practice. 

If in the future we want more accurate MIME type discovery we can rethink about it, but for the time being we can close this ticket.
