### ISSUE TITLE
User can only restrict access to departments of which they are members

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#21]
- User Jane Dow from Registrar office creates an Asset with a loan agreement document
- Jane assigns mix-in type or property to asset indicating that the asset is restricted to the Registrar staff
- Application verifies that this restriction won't lock Jane out (i.e. verify that Jane is member of Registrar dept.)
- Application is able to determine access roles based on above asset property as well as other ACLs

**Comment by scossu** [comment]
Not relevant any more.
