### ISSUE TITLE
Unexpected "department" entry in sharing table

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#211]
Wen editing sharing permissions on assets, an unexpected 'department' entry is present. See screenshot. 

![screenshot-2016-01-22_16-56-54](https://cloud.githubusercontent.com/assets/4306733/12525532/8555779e-c12a-11e5-9135-1307443b3a14.png)

**Comment by awead** [comment]
This was fixed in 01531a2e51276d5de339a3b68a06021a541ae162
