### ISSUE TITLE
Asset UI should be aware of changes in asset type

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#223]
- [x] asset type must selected
- [x] files cannot be uploaded until an asset type is chosen
- [x] asset type is "locked" once files are uploaded OR uploaded files are re-validated if asset type changes
- [x] save is prohibited unless all uploaded files match the selected asset type

**Comment by scossu** [comment]
> asset type is "locked" once files are uploaded OR uploaded files are re-validated if asset type changes

 :+1: on the former: it seems to be the most straightforward and trouble-free implementation.
