### ISSUE TITLE
Restrict search results to items with isPreferredRepresentationOf relationships

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#23]
User wants to restrict results to assets which have “aic:isPreferredRepresentationOf” relationship with Objects

**Comment by awead** [comment]
@scossu the simplest way to do this would probably be with a facet, so you have facets for relationship types and the user would select "Preferred Representation" from the list. Otherwise, I'd need a more specific UI implementation in order to proceed.

**Comment by scossu** [comment]
This is not critical for the content model. Moving to beta1.

**Comment by scossu** [comment]
To be clear about your last comment, you intend that there would be a list of on/off values, e.g. has preferred representation, has represerntation, has document?

**Comment by awead** [comment]
There'd be a solr field like "representation_sim" for Assets, and it would contain either "Representation", "Preferred Representation", or "Document" as its value. In the UI, you'd see those three terms as facet values that could be used to restrict the search.
