### ISSUE TITLE
Restrict updating licensing metadata

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#28]
As a member of the curatorial department
When I am editing a resource
Then I should not be able to edit the licensing metadata

As a member of the curatorial department
When I am viewing a resource
Then I should be able to view the licensing information

**Comment by scossu** [comment]
I would define line 3 it more clearly: 
"Then I should be able to view but not edit licensing metadata"

**Comment by awead** [comment]
@scossu these are actually two separate use cases. The first is the user is editing the resource and they should not see anything about the license. When they're viewing, they can see the information about the license. I've editing this to be two cases.
