### ISSUE TITLE
undefined method `zotero_userid'

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#30]
When navigating to the user's profile page, you get `undefined method`zotero_userid'`. Since zotero integration is out of scope, we can remove it to avoid the error.

**Comment by scossu** [comment]
Is this issue resolved? Can you close it or assign it to a different milestone?

**Comment by awead** [comment]
Fixed in 853c250049df45d75a4ceae9f115cd033f580bef
