### ISSUE TITLE
Uploading still images or text

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#32]
As an authenticated user
When I click upload
Then I should see a choice between still image or text

**Comment by awead** [comment]
No choice will be provided. Instead the user will choose which type they are uploading.

**Comment by scossu** [comment]
At which point is the decision made? I assume in the asset upload form _before_ one submits it?

**Comment by awead** [comment]
Yes, it's a dropdown menu item choice instead of a choice between paths.
