### ISSUE TITLE
Prevent uploading text files with the image upload interface

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#33]
When I'm on the still image upload page
And I upload a file with a text mime type
Then I should see and error
And the upload should not take place

**Comment by scossu** [comment]
I would rather build this condition in the parent Asset class:

When I'm on an Asset upload page
And I upload a file with a mime type that is not included in the 
accepted mime types for that asset
Then I should see and error
And the upload should not take place

Then you can define property X in Asset as an empty list of accepted 
MIME types, and override this list in Text ad StillImage. I will provide 
two lists of accepted MIME types for images and text.

**Comment by awead** [comment]
This is UI consideration. I think you're talking about the model. We can model this as you've described, but you'll still need a way for the user to indicate they're uploading a still image or text, hence the upload pages for each.

**Comment by scossu** [comment]
Correct.

**Comment by awead** [comment]
Actually, if the determination of StillImage or Text is based solely on the mime type, then this can be done automatically and there's no need for different upload pages.

**Comment by scossu** [comment]
Asset types are not driven by MIME types but by semantics. A text document for example can be a scan of a text that we can OCR. The user has to decide about the asset type.

**Comment by awead** [comment]
See https://github.com/aic-collections/aicdams-docs/blob/master/LAKE/cmodels_mime_types.md
