### ISSUE TITLE
Viewing facets for assets and files

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#35]
As a public user
When I go to the search page
Then I should see facets for assets, still images and text

**Comment by scossu** [comment]
Can still image and text facets be nested under asset?

**Comment by awead** [comment]
Yes.

**Comment by scossu** [comment]
Can image and text be visually indented under asset so they appear as refinement categories?

**Comment by awead** [comment]
Potentially, yes, but it sounds like what you want are hierarchical facets, or pivot facets as they're called in solr. Blacklight supports this, but it will take some time for me to figure it out.

**Comment by scossu** [comment]
See #71 (not in scope for current release).
