### ISSUE TITLE
Works facet

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#36]
As a public user
When I go to the search page
Then I should see a facets for works

**Comment by awead** [comment]
Fixed in b4bf1fb7ba15b9ae18dc2dcb8a2948b90d101fae

**Comment by scossu** [comment]
If the works facet is to be displayed with assets (which is correct), the facet name should be "Resource Type" instead of "Asset Type".

**Comment by awead** [comment]
This wasn't part of the original ticket, so it should be a new one. See #69
