### ISSUE TITLE
HOLD: Restrict edit fields for Works

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#37]
As an authenticated user
When I'm on the work edit page
Then I can only edit certain filelds

**Comment by scossu** [comment]
To be clear: this is a content modeling issue (fields marked as read-only for _any_ user) rather than an authorization one. So maybe "as an authenticated user" is misleading?

**Comment by awead** [comment]
Only authenticated users are allowed to edit anything. You wanted particular fields to be editable by the user, and not just all of them.

**Comment by scossu** [comment]
OK. The "authenticated user" term made me think about an auth issue.

**Comment by scossu** [comment]
Superseded by #79.
