### ISSUE TITLE
Restrict the addition of additional asset metadata to the conservation department

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#39]
As an authenticated user
When I am on the edit asset page
Then I should not be able to add additional conservation metadata

**Comment by scossu** [comment]
Reword: "As an authenticated user" > "As an authenticated user not belonging to the conservation group"

**Comment by awead** [comment]
So only members of the conservation group can edit assets?

**Comment by scossu** [comment]
I corrected the comment above. "Authenticated user" includes Conservation users, who can indeed add conservation metadata.
