### ISSUE TITLE
Restrict access to Resque admin interface

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#4]

**Comment by scossu** [comment]
Is this issue resolved? Can you close it or assign it to a different milestone?

**Comment by awead** [comment]
It's still open.

**Comment by RudyOnRails** [comment]
@awead @scossu 

Just wanted to get a hold of this issues log here before Adam transitions in a few weeks.

Was this ever completed? Does it need to be completed?

**Comment by awead** [comment]
@RudyOnRails yeah, this needs to be done. Anything below `/admin` should be restricted to admins. They are defined by a yaml file in config. There's a `user.admin?` method that takes care of this.

**Comment by RudyOnRails** [comment]
moved to https://cits.artic.edu/redmine/issues/2439
