### ISSUE TITLE
add rows option to all SolrService calls that complain

### ISSUE THREAD

**Issue by RudyOnRails** [aic-collections/aicdams-lakeshore#416]
@awead are you cool with adding `rows: 1000` to all complaining calls in support of slimming down the logs?

`Calling ActiveFedora::SolrService.get without passing an explicit value for ':rows' is not recommended. You will end up with Solr's default (usually set to 10)`

- [ ] Called by /Users/kmusio/RubymineProjects/aicdams-lakeshore/app/models/aic_user.rb:66:in `find_nick_by_solr'

- [ ] Called by /Users/kmusio/RubymineProjects/aicdams-lakeshore/app/models/concerns/citi_resource_metadata.rb:15:in `find_by_citi_uid_with_solr'

- [ ] Called by /Users/kmusio/RubymineProjects/aicdams-lakeshore/app/models/inbound_relationships.rb:67:in `resources_with'

- [ ] Called by /Users/kmusio/RubymineProjects/aicdams-lakeshore/app/models/resource.rb:43:in `solr_relation_ids'

**Comment by awead** [comment]
@RudyOnRails yes, thanks. The `find_by` methods can be `rows: 1` the others are find for 1000.
