### ISSUE TITLE
Conservation metadata should be viewable

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#42]
As a member of the conservation department
When I search using conservation department terms
Then I should see asset with those terms in the search results

**Comment by scossu** [comment]
Rephrase: 
As a member of the conservation department
I am able to search using conservation department terms
And see assets with those terms in the search results

**Comment by awead** [comment]
User stories are usually written in the "As... When... Then..." format. The idea is to describe the action the user is taking as clearly as possible. Saying that you're "able to search" may not necessarily imply that you are actually searching. Although saying "search using conservation department terms" is a bit vague too. A better, more specific user case would be:

As a member of the conservation department
When search for "special conservation term"
Then I should see Da Vinci's Last Supper in the search results

But this requires details.
