### ISSUE TITLE
HOLD: All Work metadata is viewable while editing

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#44]
As an authenticated user
When I am on the edit work page
Then I should be able to view all the fields

**Comment by scossu** [comment]
Can you articulate this?

**Comment by awead** [comment]
I was describing what you told me. All Work fields should be visible when you're editing a work, although, you only want certain fields editable.

**Comment by awead** [comment]
only the asset should be editable.

**Comment by scossu** [comment]
Superseded by #79 .
