### ISSUE TITLE
Add existing tags to assets

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#45]
As an authenticated user
When I am on the edit asset page
Then I can only add existing tags to the asset

**Comment by scossu** [comment]
This is not an auth issue, but a content modeling issue. 
"As an authenticated user" should be removed.

**Comment by awead** [comment]
This is the process for adding tags to an asset in the UI. Only authenticated users, as opposed to public, non-authenticated users, can edit any records. When I'm adding tags to an asset, then I need to be able to search through the existing tags in order to add them to the asset.
