### ISSUE TITLE
Tag categories are not available to unauthorized users

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#47]
Given there is TagCat "foo" readable by the conservation department
As an authenticated user
When I am adding a TagCat to a Tag
Then I should not see "foo" in the list of available categories

**Comment by scossu** [comment]
Rephrase: 
"When I am adding a TagCat to a Tag" -> "When I am adding a Tag to a Resource"
"Then I should not see "foo" in the list of available categories" -> "Then I should not see any tags in the "foo" category"

**Comment by awead** [comment]
This case is describing how to add categories to Tags. You're describing adding tags to resources based on what categories they have. This would be an additional case.

**Comment by scossu** [comment]
Gotcha.

**Comment by scossu** [comment]
This is deprecated due to dropping Tags and TagCategories in favor of Lists and ListItems.
