### ISSUE TITLE
Create conservation metadata class

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#49]
Belongs to 1 and only 1 asset class and contains permission restrictions so that it is only editable by members of the conservation department.

**Comment by scossu** [comment]
Permission part can be deferred to alpha3 milestone.

**Comment by scossu** [comment]
Will tackle this together with tags and tag categories.

**Comment by awead** [comment]
Addressed in 54369f614f0908258830a6c3d56b505942acf88c
