### ISSUE TITLE
Create the asset class with still images and text

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#50]
Two RDF classes, still image and text, need to be operable as Sufia's GenericFile class but must be categorically distinguished in terms of RDF class.

**Comment by scossu** [comment]
Also they should both have the Asset df type.

**Comment by awead** [comment]
I'm currently designing this so that all GenericFile objects are Assets, but that in the process of ingesting them, an additional RDF type of either StillImage or Text is applied to each. So every GenericFile would have the Asset RDF type and an additional one that is either StillImage or Text.
