### ISSUE TITLE
Add Sufia namespaces in LAKE config

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#59]
The following undeclared namespaces are found in LAKE:
PREFIX ns004: info:fedora/fedora-system:def/relations-external#
PREFIX ns003: http://scholarsphere.psu.edu/ns#
PREFIX ns002: http://id.loc.gov/vocabulary/relators/
PREFIX ns001: info:fedora/fedora-system:def/model#

**Comment by scossu** [comment]
@awead, what are the prefixes for the sufia namespaces above?

**Comment by scossu** [comment]
@awead, also: aren't the info:fedora namespaces related to Fedora 3?

**Comment by awead** [comment]
https://github.com/aic-collections/aicdams-lakeshore/blob/master/script/body.rdf

**Comment by awead** [comment]
https://github.com/aic-collections/aicdams-lakeshore/blob/master/script/fedora_config.sh

**Comment by scossu** [comment]
I have all the  namespaces defined except for 

`PREFIX ns003: <http://scholarsphere.psu.edu/ns#>`

Is that used anywhere? What is the prefix?
