### ISSUE TITLE
Restrict tag categories based on ACLs

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#6]
Each tag should be a fedora resource. The tag's category is also a fedora resource that contains access controls dictating if it's available to the user.

**Comment by awead** [comment]
@scossu to be clear, only Tags have categories that are TagCat and not Comments. Comments also have categories, but these appear to just be strings.

**Comment by scossu** [comment]
@awead That is correct. Comment categories may become entities later on 
but in Phase 1 they will be strings.

**Comment by awead** [comment]
@scossu this hasn't been implemented yet. reopening.

**Comment by scossu** [comment]
my misunderstanding. I thought this was just a question.

**Comment by scossu** [comment]
Tag categories will be replaced in favor of controlled-value properties. Closing this issue.
