### ISSUE TITLE
aic:status should be aicstatus:active by default for all resources

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#61]
Resources with aic:status not set should be ingested into LAKE wit a value of 1. At the moment, this value is not set in LAKE if it is not set in LAKEshore.

**Comment by awead** [comment]
The example Work I'm using has the URI: http://definitions.artic.edu/ontology/1.0/status/active.  Do you want to use this as opposed to 1, which is a string? Any resource created in LAKE by Hydra can have its status set accordingly. For resources that are coming from CITI and do not have their status set, it might make more sense to have that predicate set when Geneva is doing its sync.

**Comment by scossu** [comment]
That is correct, the status should be http://definitions.artic.edu/ontology/1.0/status/active.

**Comment by scossu** [comment]
Amended ticket title.
