### ISSUE TITLE
Install LibreOffce

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#63]
After install, try re-running failed derivative jobs.
https://lakeshore-test.artic.edu/admin/queues/failed

**Comment by scossu** [comment]
I have installed the following packages: 
libreoffice
libreoffice-headless
libreoffice-writer

I retried the queues but I still get the same error: 

`No such file or directory - soffice`

But on the command line, `which soffice` gives me `/usr/bin/soffice`

I also restarted httpd.

**Comment by awead** [comment]
Try uploading the same files again.

**Comment by scossu** [comment]
Thumbnails are showing for .docx , .odt and .pdf files.

**Comment by scossu** [comment]
Also works for .doc files. Not working for plain text. Is it supposed to?

**Comment by awead** [comment]
I seem to recall text files are like that, so no, I don't believe thumbnails to work for plain text files. I can investigate further, if you like.

**Comment by scossu** [comment]
See #72.
