### ISSUE TITLE
Add links to assets in work display page

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#68]
Work display page shows titles of assets correctly (e.g. <webroot>/works/6be79158-f8c2-483e-9109-43df47f8a22f) but as plain text. 

A link should be available for each asset title displayed in the work page, pointing to the asset view page.

**Comment by scossu** [comment]
Did this get reverted, or am I doing something wrong? I used to be able to see the links in a list, not anymore. 

See e.g. work ee1e7f27-34d8-4767-b6c8-6e9ec44bb291

**Comment by awead** [comment]
It wasn't reverted, there just wasn't test coverage and the changes from the latest Sufia update caused it to stop working. It's been fixed now.
