### ISSUE TITLE
Implement hierarchical (pivot) facets in Blacklight

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#71]
This is initially to support nesting of facets such as:
- Assets (10)
  - Text (6)
  - Still Image (4)

But should be flexible enough to accommodate further use cases.

**Comment by awead** [comment]
@scossu I've moved this to alpha4, but you might want to put it in beta1 or later. It will take more time to implement.

**Comment by scossu** [comment]
This will need hierarchical lists resolved first.

**Comment by scossu** [comment]
Migrated to CITS.
