### ISSUE TITLE
Implement advanced search

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#73]

**Comment by scossu** [comment]
Optional for alpha2.

**Comment by awead** [comment]
It's already there - https://lakeshore-test.artic.edu/search Note, this is the default and needs some customization. Let me what changes you want and if you want it inserted into the right-hand section of the homepage. Might have some screen real estate issues...

**Comment by scossu** [comment]
That is a good start. The fields are not the ones we need but I will address that in a separate issue. 

The design is responsive and it can fit in the homepage layout. If you can complete the following you can close the ticket: 
- Insert the advanced search view in the home page area 
- Remove "more search options" title 
- Remove last duplicated point in search tips: "truncation and wildcards..."

**Comment by scossu** [comment]
Addition: 

Remove both "truncation and wildcards..." points in search tips
