### ISSUE TITLE
Improve error message when deleting assets with incoming links

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#77]
If I link an asset to a work (via the "asset ids" property in the work) and try to delete that asset, I get a generic "Somethig went wrong" page. 

I expect to see an error page with details about the reason which asset cannot be deleted and why - i.e. which resources have relationships with it.

**Comment by awead** [comment]
Looks like this is a bug in ActiveFedora. See projecthydra/active_fedora#873

A workaround is to remove the asset from the work first, then delete the asset.

**Comment by scossu** [comment]
That is right, but this issue is about the error message, not the workflow. The application should warn a user with a clear message about what they are doing wrong.

**Comment by awead** [comment]
All they would get is an HTTP 500 error.

**Comment by scossu** [comment]
500 is a server error, but the server is not to blame in this case. 

The server should return 400 Bad Request or, even better, 409 Conflict (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10) because this is a client error. 

As such, the server should explain the reason for the failure.

**Comment by awead** [comment]
Rails will only return the specific HTTP error, unless you want a stack trace, which I don't recommend.

**Comment by scossu** [comment]
The point is to throw the correct HTTP error. 500 is not correct IMO.

**Comment by awead** [comment]
I can return whatever the application throws. Whether it's "correct" I don't have control over.

**Comment by scossu** [comment]
We can discuss this further over the next meeting.

**Comment by awead** [comment]
@scossu this has changed. Now, you can delete the asset without any problems. Do you want to prevent deleting any assets with incoming links?

**Comment by scossu** [comment]
In theory it may be desirable to be able to delete an asset even if it has incoming links, but there would be two side effects to that: 
1. Relationships in the linked resources are deleted in Fedora without Sufia knowing (unless Sufia goes first and explicitly deletes the relationships). In either case this change _should_ eventually circle back via the Camel update functionality, but it has to be tested. 
2. By implicitly deleting relationships in a resource linked to the deleted asset, one is effectively updating that resource. The user deleting the asset may not have write permission on some of the resources that are being implicitly changed and this may lead to complications. 

That said, given that deleting assets should be done with care, especially if other resources are depending on them, I would lean toward a conservative approach and require that the user explicitly removes the relationships before they can delete the asset.

**Comment by scossu** [comment]
In practice, this issue is still valid. The server should send a 400 error page with an explanation text: "This asset cannot be deleted because it is referred to by other resources. Please remove the references to this asset from the following resources before proceeding:"

Follows a list of links to the depending resources and a "retry" button that repeats the request

**Comment by awead** [comment]
The resources that are updated, ex. Works, Actors, etc., don't have permissions enabled on them, so any valid user is able to edit them, however, the assets themselves are fully-controlled via Hydra permissions.

**Comment by scossu** [comment]
CITI resources should become access controlled after beta1, so I prefer setting this behavior now.

**Comment by awead** [comment]
I'll enable it for Assets (GenericFiles) and then enable it for the CITI resources once they have permissions defined on them.
