### ISSUE TITLE
Assets table / manager

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#79]
- Create a partial view with a table that displays all the assets related to a resource
- The table should look for the following properties on the interested resource:
  - `aic:hasAsset`
  - `aic:hasDocument`
  - `aic:hasRepresentation`
  - `aic:hasPreferredRepresentation`
- Add this table to all the view pages for Works (Objects) and Assets (assets can have related assets as well).
- The table contains the following fields: 
  - Asset thumbnail
  - Relationship (human-readable label of relationship property)
  - Asset ID with link to asset view page
  - Asset type (text, still image, etc.)
  - Button to remove the relationship if current user has write permissions to resource
- Add a field above the table to allow adding relationships and a submit button (if user has write permissions). If one or more relationships are added, refresh the page

**Comment by awead** [comment]
A wireframe would be really helpful here.

**Comment by scossu** [comment]
Closing in favor of #86 and individual content model issues.
