### ISSUE TITLE
API: Create new resource

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#8]
1. User POSTs image file(s) with metadata
2. Application validates bitstream(s) and metadata
3. Application calls external service to mint new AIC-specific UID 
4. Application starts transaction in Fedora
5. Application creates container hierarchy and populates them with metadata
6. Application ingests binary files
7. Application commits transaction on success, or rolls back on failure
8. Server returns 201 with location header on success or 4XX error on failure

**Comment by scossu** [comment]
@awead : are we depending on any Hydra core features to implement this?

**Comment by awead** [comment]
@scossu not unless you want true transactions, which aren't supported by Hydra. I know Fedora has them, but Hydra doesn't have a way of using them. However, I'm not seeing the benefits of transactions. In Hydra, creating the resource will either succeed or fail. A possible solution is separate the metadata creation from the content upload. A possible scenario is that you could end up with a resource with description, but no content if the upload process somehow doesn't succeed. In that case, you would just re-upload the content again.

**Comment by scossu** [comment]
We can wait until Hydra supports Fedora transactions to decide whether 
we need/want to implement them.

**Comment by RudyOnRails** [comment]
This is completed I assume, right? Creating new assets via API?
