### ISSUE TITLE
Word stemming

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#82]
Advanced search legend refers to "word stemming" - which to my knowledge means that if I enter "seat" or "rain" as a search term, I should find records containing respectively "seated" or "rainy". 

This does not happen currently in test. Is stemming actually disabled or do we need a more specific definition of this capability?

**Comment by awead** [comment]
This deals with solr and Blacklight configuration. I'll need an explicit use case before I can proceed.

**Comment by scossu** [comment]
See the two use cases in the OP. At the moment I am just asking if stemming is supported and to which extent, so the legend can be made more specific (I doubt more than a few end users know what "word stemming" means).

**Comment by awead** [comment]
Stemming is supported via Solr and there are many options, the default is a Porter stemmer, but you can use other depending on your specific use cases.

**Comment by scossu** [comment]
Thanks, I will open a separate issue to support stemming. 

So is it safe to remove the mention to word stemming until we actually implement it?

**Comment by awead** [comment]
Sure.
