### ISSUE TITLE
Advanced search by resource type does not work

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#83]
In advanced search page, entering "Work" as resource type search term yields no results. However, restricting results by Work facets works.

**Comment by awead** [comment]
That's a different resource_type field that's in Sufia and isn't the same. I wouldn't recommend using "work" as a search term. If you want to search works, I'd use the dropdown option we have, or limit using facets.

**Comment by scossu** [comment]
:ok_hand:  A dropdown would be optimal. Also, is there a reason why the "resource type" field in advanced search is different from the facet, and could these be merged?
