### ISSUE TITLE
Create placeholder groups and assign users

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#84]
While a full integration with directory services to obtain user and group information is not in place, we need some sample users and group to build authZ scenarios and use cases: 
- Create "IS", "Registration" and "Conservation" groups
- Assign (already existing) users to groups: 
  - scossu to IS (also admin)
  - test_registrar to Registration
  - test_conservator to Conservation

**Comment by scossu** [comment]
@awead , you mentioned that user/group assignment changed recently in Sufia. Can you point out to the correct configuration files?

**Comment by awead** [comment]
It's been moved to this gem: https://github.com/projecthydra/hydra-role-management
