### ISSUE TITLE
API: Search related images

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#9]
- Client requests all assets of Image type related to CITI object with ID 12345 by providing parameters in JSON format
- Server interprets query terms and translates them into a SPARQL or Solr query
- Results are returned in JSON (possibly JSON-LD) format

**Comment by RudyOnRails** [comment]
Closing, as issue was resolved/merged in https://github.com/aic-collections/aicdams-lakeshore/pull/232

**Comment by RudyOnRails** [comment]
@scossu @awead please confirm I'm correct in closing this issue based on PR 232...
