### ISSUE TITLE
Create List and ListItem content models

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#93]
See alpha3 content model spreadsheet for reference.

Stefano to provide sample list resources in lake-test

**Comment by awead** [comment]
Closed via df19c7261ffb305f990951fa6df48e14ea3242ec

**Comment by scossu** [comment]
How do I test this? Is there a GUI to create, remove and assign list items?

**Comment by awead** [comment]
No. That was not part of the ticket. It was my understanding that lists would be created via Geneva.

**Comment by scossu** [comment]
It was not but we discussed the utility of it to create initial lists and from the discussion I understood that it was relatively straightforward to implement. I will open a separate issue on beta1.

**Comment by scossu** [comment]
Related issue: #130
