### ISSUE TITLE
Can't enforce cardinality on ActiveTriples::Resource properties

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#98]
ListItem types should be a kind of ActiveTriples::Resource, but ActiveFedora won't allow you to declare these as singular.

**Comment by scossu** [comment]
This seems to belong to alpha4 since it is validation-related, do you agree @awead ?

**Comment by awead** [comment]
This isn't an issue anymore because we're using AF::Base objects for list items.
